# -*- coding: utf-8 -*-
"""DDP_Pertemuan 5 Muhammad Rafly Fauzan_SI02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FusjcmkPWySdHbR1PxQ9CeIvYDR8Ihh
"""

#soal no 1
kendaraan = ['honda','motor vario',150,'hitam', 5]
print("kendaraan saya")
print(kendaraan)
print("=========")

kendaraan.extend([250000000, "matic"])
print(kendaraan)

#tambahkan setelah jenis kendaraan value [merk kendaraan].
kendaraan.insert(5, 'honda')
print(kendaraan)

#soal no 2
print("Ini adalah program sederhana untuk menghitung luas bangun datar")
print("Pilih menu angka 1-3 : \n1 . persegi\n2. lingkaran\n3. segitiga")
pilihMenu = int(input("Silahkan pilih menu dengan mengetikan angka 1-3 : "))

match pilihMenu:
    case 1:
        print("Ini adalah menu untuk menghitung luas persegi")
        sisi= int(input("Silahkan masukan nilai yang mau dihitung :"))
        hitung= sisi * sisi
        print(f"Luas persegi adalah: {hitung}")

    case 2:
        print("ini adalah menu untuk menghitung luas lingkaran")
        r = int(input("masukan nilai yang ingin di hitung"))
        phi = 3.14
        luas = phi*r*r
        print (int(luas))

    case 3:
        print("ini adalah menu untuk menghitung luas segitiga")
        alas= int(input("masukan alas"))
        tinggi= int(input("masukan tinggi"))

        luas_segitiga= int(1/2*alas*tinggi)
        print(f'luas segitiga = 1/2 ', alas, '', tinggi, '=', luas_segitiga)
    case _:
        print("pilihan tidak valid, silahkan pilih antar 1-3")